# Generated by Django 5.2.6 on 2025-09-17 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliography', '0003_remove_bibliografia_usuario_bibliography_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbol_json', models.JSONField()),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('seed', models.TextField(help_text='Semilla utilizada para generar el árbol')),
                ('title', models.CharField(blank=True, help_text='Título del árbol generado', max_length=255)),
                ('bibliography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to='bibliography.bibliography')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Árbol de la Ciencia',
                'verbose_name_plural': 'Árboles de la Ciencia',
                'db_table': 'tree',
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
