# Generated by Django 5.2.6 on 2025-09-13 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliografia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arbolciencia',
            name='bibliografia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibliography.bibliografia'),
        ),
    ]
