# Generated by Django 5.2.6 on 2025-09-17 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliografia',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='bibliography/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliographies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bibliografía',
                'verbose_name_plural': 'Bibliografías',
                'db_table': 'bibliography',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.DeleteModel(
            name='ArbolCiencia',
        ),
        migrations.DeleteModel(
            name='Bibliografia',
        ),
    ]
