# Generated by Django 5.2.8 on 2025-11-20 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptada'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_file', models.FileField(upload_to='queries/%Y/%m/%d/')),
                ('processing_state', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Error')], default='PENDING', max_length=10)),
                ('tree_data', models.JSONField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'db_table': 'queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento de login fallido'), ('INVITATION_SENT', 'Invitación enviada'), ('INVITATION_ACCEPTED', 'Invitación aceptada'), ('PROFILE_UPDATED', 'Perfil actualizado'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('ACCOUNT_ACTIVATED', 'Cuenta activada'), ('ACCOUNT_SUSPENDED', 'Cuenta suspendida'), ('ADMIN_ACTION', 'Acción administrativa')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_state',
            field=models.CharField(choices=[('PENDING', 'Pendiente de verificación'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INVITED', 'Invitado')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_state'], name='auth_user_user_st_b0d698_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='auth_user_is_veri_c40f2e_idx'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email'], name='invitations_email_6e7169_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['state'], name='invitations_state_663e14_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='invitations_expires_7f52c2_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['user', 'created_at'], name='queries_user_id_6879d0_idx'),
        ),
        migrations.AddIndex(
            model_name='query',
            index=models.Index(fields=['processing_state'], name='queries_process_ee72ba_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'created_at'], name='user_activi_user_id_c742e0_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='user_activi_activit_534635_idx'),
        ),
    ]
