# Generated by Django 5.2.8 on 2025-11-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_adminrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.CharField(choices=[('PENDING', 'Pendiente de verificación'), ('ACTIVE', 'Activo'), ('SUSPENDED', 'Suspendido'), ('INVITED', 'Invitado')], default='ACTIVE', max_length=10),
        ),
    ]
