# Generated by Django 5.2.8 on 2025-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invitation_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
