# Generated by Django 5.2.8 on 2026-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_invitation_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('administrator', 'Administrador')], default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='invitation_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
