# Generated by Django 5.2.8 on 2026-03-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_invitation_role_alter_user_invitation_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
    ]
